"""Overview of models.

This module bundles models logic for the kgfoundry stack. It groups related helpers so downstream
packages can import a single cohesive namespace. Refer to the functions and classes below for
implementation specifics.
"""

# [nav:section public-api]

from __future__ import annotations

from typing import ClassVar, Literal

from pydantic import ConfigDict, Field

from kgfoundry_common.navmap_loader import load_nav_metadata
from kgfoundry_common.pydantic import BaseModel

__all__ = [
    "Chunk",
    "Doc",
    "DoctagsAsset",
    "Id",
    "LinkAssertion",
]
__navmap__ = load_nav_metadata(__name__, tuple(__all__))


# [nav:anchor Id]
type Id = str


# [nav:anchor Doc]
class Doc(BaseModel):
    """Document model representing academic papers and publications.

    Pydantic model for representing document metadata including identifiers
    (OpenAlex, DOI, arXiv, PMCID), bibliographic information, and file
    references. Field descriptions below include alias behaviour for
    reproducibility across serialization boundaries.

    Attributes
    ----------
    model_config : ClassVar[object]
        Pydantic configuration forbidding unknown fields.
    id : Id
        Unique document identifier.
    openalex_id : str | None
        OpenAlex work identifier.
    doi : str | None
        Digital Object Identifier.
    arxiv_id : str | None
        arXiv preprint identifier.
    pmcid : str | None
        PubMed Central identifier.
    title : str
        Document title.
    authors : list[str]
        List of author names.
    pub_date : str | None
        Publication date string.
    license : str | None
        License identifier (for example ``"CC-BY"``).
    language : str | None
        Two-letter language code.
    pdf_uri : str
        URI or path to the PDF file.
    source : str
        Source identifier (for example ``"openalex"``).
    content_hash : str | None
        SHA256 content hash for deduplication.

    Examples
    --------
    >>> from pathlib import Path
    >>> from kgfoundry_common.schema_helpers import assert_model_roundtrip
    >>> example_path = (
    ...     Path(__file__).parent.parent.parent / "schema" / "examples" / "models" / "doc.v1.json"
    ... )
    >>> assert_model_roundtrip(Doc, example_path)
    """

    model_config: ClassVar[object] = ConfigDict(extra="forbid")
    """Pydantic configuration forbidding unknown fields."""

    id: Id
    """Unique document identifier.

    Alias: none; uses field name ``id``.
    """
    openalex_id: str | None = None
    """OpenAlex work identifier.

    Alias: none; canonical name ``openalex_id``.
    """
    doi: str | None = None
    """Digital Object Identifier.

    Alias: none; canonical name ``doi``.
    """
    arxiv_id: str | None = None
    """ArXiv preprint identifier.

    Alias: none; canonical name ``arxiv_id``.
    """
    pmcid: str | None = None
    """PubMed Central identifier.

    Alias: none; canonical name ``pmcid``.
    """
    title: str = ""
    """Document title.

    Alias: none; canonical name ``title``.
    """
    authors: list[str] = Field(default_factory=list)
    """List of author names.

    Alias: none; canonical name ``authors``.
    """
    pub_date: str | None = None
    """Publication date string.

    Alias: none; canonical name ``pub_date``.
    """
    license: str | None = None
    """License identifier (for example ``"CC-BY"``).

    Alias: none.
    """
    language: str | None = "en"
    """Two-letter language code.

    Alias: none; canonical name ``language``.
    """
    pdf_uri: str = ""
    """URI or path to the PDF file.

    Alias: none; canonical name ``pdf_uri``.
    """
    source: str = "unknown"
    """Source identifier (for example ``"openalex"``).

    Alias: none.
    """
    content_hash: str | None = None
    """SHA256 content hash for deduplication.

    Alias: none; canonical name ``content_hash``.
    """


# [nav:anchor DoctagsAsset]
class DoctagsAsset(BaseModel):
    """Doctags asset model for visual document tags.

    Pydantic model representing doctag metadata generated by vision-language models. Inline
    attribute docstrings capture alias usage for each field.
    """

    doc_id: Id
    """Document identifier that owns this asset.

    Alias: none; name ``doc_id``.
    """
    doctags_uri: str
    """Path or URI to the doctags artefact.

    Alias: none; name ``doctags_uri``.
    """
    pages: int
    """Total page count represented by the doctags file.

    Alias: none.
    """
    vlm_model: str
    """Vision-language model identifier.

    Alias: none; name ``vlm_model``.
    """
    vlm_revision: str
    """Model revision or version string.

    Alias: none; name ``vlm_revision``.
    """
    avg_logprob: float | None = None
    """Average log-probability score.

    Alias: none; name ``avg_logprob``.
    """


# [nav:anchor Chunk]
class Chunk(BaseModel):
    """Document chunk model for text segmentation.

    Represents a contiguous span of text with doctag mappings. Attribute docstrings note alias
    behaviour explicitly.
    """

    id: Id
    """Unique chunk identifier.

    Alias: none; name ``id``.
    """
    doc_id: Id
    """Document identifier that owns the chunk.

    Alias: none; name ``doc_id``.
    """
    section: str | None
    """Optional section label.

    Alias: none; name ``section``.
    """
    start_char: int
    """Inclusive starting character offset.

    Alias: none; name ``start_char``.
    """
    end_char: int
    """Exclusive ending character offset.

    Alias: none; name ``end_char``.
    """
    tokens: int
    """Token count for the chunk.

    Alias: none; name ``tokens``.
    """
    doctags_span: dict[str, int]
    """Mapping of doctag page identifiers to character offsets.

    Alias: none.
    """


# [nav:anchor LinkAssertion]
class LinkAssertion(BaseModel):
    """Link assertion model for knowledge graph connections.

    Encodes a connection between a document chunk and a knowledge graph concept with scoring
    metadata. Inline docstrings enumerate alias usage.
    """

    id: Id
    """Unique link assertion identifier.

    Alias: none; name ``id``.
    """
    chunk_id: Id
    """Identifier of the associated chunk.

    Alias: none; name ``chunk_id``.
    """
    concept_id: Id
    """Knowledge graph concept identifier.

    Alias: none; name ``concept_id``.
    """
    score: float
    """Confidence score for the link.

    Alias: none; name ``score``.
    """
    decision: Literal["link", "reject", "uncertain"]
    """Decision outcome for the link.

    Alias: none; name ``decision``.
    """
    evidence_span: str | None = None
    """Optional supporting text span.

    Alias: none; name ``evidence_span``.
    """
    features: dict[str, float] = Field(default_factory=dict)
    """Feature vector metadata.

    Alias: none; name ``features``.
    """
    run_id: str
    """Identifier of the ingestion run.

    Alias: none; name ``run_id``.
    """
