"""Overview of api.

This module bundles api logic for the kgfoundry stack. It groups related helpers so downstream
packages can import a single cohesive namespace. Refer to the functions and classes below for
implementation specifics.
"""

# [nav:section public-api]

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from kgfoundry_common.navmap_loader import load_nav_metadata

if TYPE_CHECKING:
    from collections.abc import Mapping

    from kgfoundry_common.models import Doc, DoctagsAsset

__all__ = [
    "Registry",
]
__navmap__ = load_nav_metadata(__name__, tuple(__all__))


# [nav:anchor Registry]
class Registry(Protocol):
    """Protocol defining the registry interface for pipeline artifacts.

    This protocol defines the interface for registry implementations that store pipeline artifacts
    and metadata. Implementations must provide methods for managing runs, datasets, documents,
    doctags, and events.

    Implementations include DuckDBRegistry and DuckDBRegistryHelper.
    """

    def begin_dataset(self, kind: str, run_id: str) -> str:
        """Begin a new dataset within a run.

        Creates a new dataset record associated with the specified run.
        The dataset is initially created with an empty parquet_root; use
        commit_dataset() to finalize it with data.

        Parameters
        ----------
        kind : str
            Dataset kind (e.g., "embeddings", "chunks", "metadata").
        run_id : str
            Run ID that this dataset belongs to.

        Returns
        -------
        str
            Unique dataset ID (UUID) for the newly created dataset.
        """
        ...

    def commit_dataset(self, dataset_id: str, parquet_root: str, rows: int) -> None:
        """Commit a dataset with Parquet data location.

        Finalizes a dataset by updating its parquet_root path and row count.
        Used after Parquet files have been written to disk.

        Parameters
        ----------
        dataset_id : str
            Dataset ID to commit.
        parquet_root : str
            Root directory path where Parquet files are stored.
        rows : int
            Total number of rows in the dataset.
        """
        ...

    def rollback_dataset(self, dataset_id: str) -> None:
        """Rollback a dataset by deleting it.

        Deletes a dataset record when dataset creation fails or needs to
        be abandoned. Use this for cleanup when errors occur.

        Parameters
        ----------
        dataset_id : str
            Dataset ID to rollback.
        """
        ...

    def insert_run(
        self,
        purpose: str,
        model_id: str | None,
        revision: str | None,
        config: Mapping[str, object],
    ) -> str:
        """Create a run record and return the generated identifier.

        Inserts a new run record into the registry with the specified purpose,
        model information, and configuration. Returns a unique run ID.

        Parameters
        ----------
        purpose : str
            Purpose description for the run (e.g., "embedding", "indexing").
        model_id : str | None
            Model identifier used in this run, or None if not applicable.
        revision : str | None
            Model revision or version, or None if not applicable.
        config : Mapping[str, object]
            Run configuration dictionary (serialized as JSON).

        Returns
        -------
        str
            Unique run ID (UUID) for the newly created run.
        """
        ...

    def close_run(self, run_id: str, *, success: bool, notes: str | None = None) -> None:
        """Close a pipeline run and record completion status.

        Updates the run's finished_at timestamp and records completion status
        with optional notes.

        Parameters
        ----------
        run_id : str
            Run ID to close.
        success : bool
            Whether the run completed successfully.
        notes : str | None, optional
            Optional notes about the run completion. Defaults to None.
        """
        ...

    def register_documents(self, docs: list[Doc]) -> None:
        """Register document records in the registry.

        Inserts or updates document records in the documents table. Each
        document's metadata (title, authors, publication date, etc.) is
        stored with the document ID.

        Parameters
        ----------
        docs : list[Doc]
            List of document objects to register. Each document must have
            a unique doc_id.
        """
        ...

    def register_doctags(self, assets: list[DoctagsAsset]) -> None:
        """Register doctags asset records in the registry.

        Inserts or updates doctags asset records in the doctags table.
        Doctags represent visual document tags generated by vision-language
        models.

        Parameters
        ----------
        assets : list[DoctagsAsset]
            List of doctags asset objects to register. Each asset must have
            doc_id, doctags_uri, and model information.
        """
        ...

    def emit_event(self, event_name: str, subject_id: str, payload: Mapping[str, object]) -> None:
        """Emit a pipeline event to the registry.

        Records an event in the pipeline_events table with a unique event ID,
        event name, subject ID, and JSON payload. Used for tracking pipeline
        operations and state changes.

        Parameters
        ----------
        event_name : str
            Name of the event (e.g., "RunClosed", "DatasetCommitted").
        subject_id : str
            ID of the subject the event relates to (e.g., run_id, dataset_id).
        payload : Mapping[str, object]
            Event payload dictionary (serialized as JSON).
        """
        ...

    def incident(self, event: str, subject_id: str, error_class: str, message: str) -> None:
        """Record an incident emitted by registry clients.

        Inserts an incident record into the incidents table for tracking
        errors and failures in pipeline operations.

        Parameters
        ----------
        event : str
            Event name associated with the incident.
        subject_id : str
            ID of the subject the incident relates to (e.g., run_id, dataset_id).
        error_class : str
            Error class or exception type name.
        message : str
            Error message describing the incident.
        """
        ...
