"""Coverage analytics pipeline orchestration.

This module provides high-level pipeline functions for running coverage analytics,
test analytics, and risk factor computation. Orchestrates the execution of
coverage line extraction, function aggregation, test catalog building, and
risk factor computation workflows.
"""

from __future__ import annotations

import json
from pathlib import Path

from codeintel_rev.services.enrich.coverage_functions import (
    aggregate_coverage_functions,
    write_coverage_functions,
)
from codeintel_rev.services.enrich.coverage_lines import iter_coverage_lines, write_coverage_lines
from codeintel_rev.services.enrich.goid_utils import build_function_span_index, load_goid_registry
from codeintel_rev.services.enrich.risk_factors import build_goid_risk_factors, write_risk_factors
from codeintel_rev.services.enrich.test_catalog import build_test_catalog, write_test_catalog
from codeintel_rev.services.enrich.test_coverage_edges import (
    build_test_coverage_edges,
    write_test_coverage_edges,
)


def _load_repo_meta(enriched_dir: Path) -> tuple[str, str]:
    repo_map = enriched_dir / "repo_map.json"
    if not repo_map.exists():
        return "", ""
    payload = json.loads(repo_map.read_text(encoding="utf-8"))
    return str(payload.get("repo") or ""), str(payload.get("commit") or "")


def run_coverage_analytics(
    *,
    repo_root: Path,
    enriched_dir: Path,
    coverage_file: Path,
) -> tuple[Path, Path]:
    """Compute coverage_lines and coverage_functions artifacts.

    Extended Summary
    ----------------
    Orchestrates the coverage analytics pipeline: extracts per-line coverage
    data, writes coverage_lines artifact, then aggregates to per-function
    metrics and writes coverage_functions artifact. Loads repository metadata
    and GOID registry to support function-level aggregation.

    Parameters
    ----------
    repo_root : Path
        Root directory of the repository being analyzed.
    enriched_dir : Path
        Directory containing enriched analytics artifacts. Must contain
        repo_map.json for repository metadata and GOID registry files.
    coverage_file : Path
        Path to coverage.py data file (.coverage) containing coverage measurements.

    Returns
    -------
    tuple[Path, Path]
        Tuple containing (coverage_lines_path, coverage_functions_path) where
        both paths point to Parquet files written to enriched_dir/analytics/coverage/.
        The coverage_lines_path contains per-line coverage data, and
        coverage_functions_path contains aggregated per-function metrics.

    Notes
    -----
    Time O(n + m) where n is number of executable lines and m is number of functions;
    memory O(n) for loading coverage lines and GOID registry. Performs file I/O
    to read coverage data, GOID registry, and write analytics artifacts.
    Creates output directory structure if it doesn't exist.
    """
    repo, commit = _load_repo_meta(enriched_dir)
    coverage_dir = enriched_dir / "analytics" / "coverage"
    coverage_dir.mkdir(parents=True, exist_ok=True)

    line_rows = list(
        iter_coverage_lines(
            repo=repo,
            commit=commit,
            repo_root=repo_root,
            coverage_file=coverage_file,
        )
    )
    coverage_lines_path = coverage_dir / "coverage_lines.parquet"
    write_coverage_lines(line_rows, coverage_lines_path)

    goids = load_goid_registry(enriched_dir)
    function_rows = aggregate_coverage_functions(
        goids=goids,
        coverage_lines_path=coverage_lines_path.with_suffix(".jsonl"),
        repo=repo,
        commit=commit,
    )
    coverage_functions_path = coverage_dir / "coverage_functions.parquet"
    write_coverage_functions(function_rows, coverage_functions_path)
    return coverage_lines_path, coverage_functions_path


def run_test_analytics(
    *,
    repo_root: Path,
    enriched_dir: Path,
    coverage_file: Path,
    pytest_report: Path,
) -> tuple[Path, Path]:
    """Compute test_catalog and test_coverage_edges artifacts.

    Extended Summary
    ----------------
    Orchestrates the test analytics pipeline: builds test catalog from pytest
    report, writes test_catalog artifact, then computes test-to-function coverage
    edges and writes test_coverage_edges artifact. Requires coverage_functions.jsonl
    to exist (generated by run_coverage_analytics).

    Parameters
    ----------
    repo_root : Path
        Root directory of the repository being analyzed.
    enriched_dir : Path
        Directory containing enriched analytics artifacts. Must contain
        repo_map.json, GOID registry, and coverage_functions.jsonl.
    coverage_file : Path
        Path to coverage.py data file (.coverage) for computing coverage edges.
    pytest_report : Path
        Path to pytest JSON report generated via pytest-json-report plugin.

    Returns
    -------
    tuple[Path, Path]
        Tuple containing (test_catalog_path, edges_path) where both paths point
        to Parquet files written to enriched_dir/analytics/tests/. The
        test_catalog_path contains test metadata, and edges_path contains
        test-to-function coverage relationships.

    Notes
    -----
    Time O(n + m + k) where n is number of tests, m is number of functions,
    and k is number of coverage contexts; memory O(n + m) for loading test
    catalog and function spans. Performs file I/O to read pytest report,
    coverage data, and write analytics artifacts. Creates output directory
    structure if it doesn't exist.
    """
    repo, commit = _load_repo_meta(enriched_dir)
    tests_dir = enriched_dir / "analytics" / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    goids = load_goid_registry(enriched_dir)
    test_rows = build_test_catalog(
        repo=repo,
        commit=commit,
        repo_root=repo_root,
        goids=goids,
        pytest_report=pytest_report,
    )
    test_catalog_path = tests_dir / "test_catalog.parquet"
    write_test_catalog(test_rows, test_catalog_path)

    span_index = build_function_span_index(goids)
    coverage_functions_path = enriched_dir / "analytics" / "coverage" / "coverage_functions.jsonl"
    edge_rows = build_test_coverage_edges(
        repo_root=repo_root,
        span_index=span_index,
        coverage_file=coverage_file,
        test_catalog_path=test_catalog_path.with_suffix(".jsonl"),
        coverage_functions_path=coverage_functions_path,
    )
    edges_path = tests_dir / "test_coverage_edges.parquet"
    write_test_coverage_edges(edge_rows, edges_path)
    return test_catalog_path, edges_path


def run_risk_factors(enriched_dir: Path) -> Path:
    """Compute goid_risk_factors from analytics artifacts.

    Extended Summary
    ----------------
    Computes risk factors for function GOIDs based on coverage analytics and
    writes goid_risk_factors artifact. Aggregates risk metrics from coverage
    data to identify high-risk functions (untested, low coverage, etc.).

    Parameters
    ----------
    enriched_dir : Path
        Directory containing enriched analytics artifacts. Must contain
        coverage_functions.jsonl and other required analytics files.

    Returns
    -------
    Path
        Path to Parquet file written to enriched_dir/analytics/risk/goid_risk_factors.parquet
        containing risk factor metrics per function GOID.

    Notes
    -----
    Time O(n) where n is number of functions; memory O(n) for loading coverage
    functions and computing risk factors. Performs file I/O to read analytics
    artifacts and write risk factors. Creates output directory structure if
    it doesn't exist.
    """
    risk_dir = enriched_dir / "analytics" / "risk"
    risk_dir.mkdir(parents=True, exist_ok=True)
    rows = build_goid_risk_factors(enriched_dir)
    out_path = risk_dir / "goid_risk_factors.parquet"
    write_risk_factors(rows, out_path)
    return out_path
